### ISSUE TITLE
width/height inline CSS doesn't have units

### ISSUE THREAD

**Issue by vincentaudebert** [MoOx/react-svg-inline#1]
Any reason why the inline CSS for width/height doesn't have unit?
It makes the icons break my design on Firefox.

It should specify px unit.

**Comment by MoOx** [comment]
width and height props expect strings, with unit. If we force px how can we use % for example?

**Comment by vincentaudebert** [comment]
Oh wow sorry about this... Totally misread the code.
I thought https://github.com/MoOx/react-svg-inline/blob/master/src/index.js#L15 was actually removing the units.

Closing non-issue :)
Great package btw, thanks for sharing!
