### ISSUE TITLE
Why raw-loader required?

### ISSUE THREAD

**Issue by jerrygreen** [MoOx/react-svg-inline#10]
Time to time I want to use svg as a background property in styles. In this case I need a link to svg, not its content.

Does raw-loader really needed?

**Comment by MoOx** [comment]
If you send directly svg as a string to this component, it's not required indeed. raw-loader is just recommended to require() svg files.

**Comment by MoOx** [comment]
If you want to use svg as background, then this component (which purpose is to inline an svg) does not make sense.

**Comment by jerrygreen** [comment]
@MoOx but I can't use file-loader and pass a string (which is an url) to your component to the svg, can I?

**Comment by MoOx** [comment]
This component accept a raw svg (string). Don't make sense for something else. If you want a background, use css.
