### ISSUE TITLE
How can I use it with a svg file which contains all the svg icon?

### ISSUE THREAD

**Issue by wqcstrong** [MoOx/react-svg-inline#11]
If a svg file which contains all the svg icon, then how can i use it?
For example, I used it `<svg><use xlink:href='myicon.svg#icon-plus'></use></svg>`.
Now,how can I used it with react-svg-inline?

**Comment by MoOx** [comment]
Does not make sense to use this component with this kind of svg imo.

**Comment by wqcstrong** [comment]
I know! I know! I would like to ask you about....can you teach me how to use svg? As mentioned above-----If a svg file which contains all the svg icon, then how can i use it?
Do you have a great or perfect solution to solve it ?Looking forward to your reply！

**Comment by MoOx** [comment]
Keep thing simple: don't use an SVG sprite, just use normal (multiples) SVGs files with webpack raw-loader.

**Comment by wqcstrong** [comment]
OK!  Thanks for your suggestion.Your advice is often really practical if I just import one/two or more svg from their corresponding files in a component.But I usually consider that  may be redundancy  when I have many svg icons files in a component,I have to import svg  from '*.svg' many times under the circumstances.So,is there a better solution?

**Comment by MoOx** [comment]
Not from what I know :/

**Comment by wqcstrong** [comment]
Anyway,you have helped me a lot, thank you.If you find a solution to what I said above, please tell me.Of course, if I find a solution, I will continue to reply to you here.Thank you and your advice.
