### ISSUE TITLE
Option to easily add filters?

### ISSUE THREAD

**Issue by Indigo744** [MoOx/react-svg-inline#14]
Hello,

I really like your component. It's nice and efficient.

However, I would like to be able to add some filter on my SVG at runtime.

I don't think it is easily possible in current state. Do you think something like this could be added?

Thanks.

**Comment by MoOx** [comment]
Not sure that's should be in the scope of this project. Manipulating filters have nothing to do with display a svg using dangerousInnerHtml. Hope you will find a solution if not already done
