### ISSUE TITLE
Remove wrapping tag

### ISSUE THREAD

**Issue by jdockwarder** [MoOx/react-svg-inline#16]
I love using this module, as it is the only one fulfilling my needs. The only thing bugging me is that every SVG will be wrapped inside a span by default. I'd love an option to disable the wrapper. At least I couldn't figure out how to remove the span using the component prop.

**Comment by MoOx** [comment]
This module is dangerousSetInnetHTML react feature. You cannot easily just transform a string as a react component. So it has to be wrapped.

**Comment by silverwind** [comment]
> You cannot easily just transform a string as a react component

It's actually not that hard. I created [react-svg-raw](https://github.com/silverwind/react-svg-raw) for wrapper-less SVGs. 😉
