### ISSUE TITLE
Why are fills removed?

### ISSUE THREAD

**Issue by aaronbeall** [MoOx/react-svg-inline#19]
Why are fills removed? I'm using [google material design icons](https://github.com/google/material-design-icons) and some of them use fills. They render incorrectly with svg inline because the fills gets stripped out.

**Comment by MoOx** [comment]
See https://github.com/MoOx/react-svg-inline#cleanup.
It's a default behavior that you can adjust.

**Comment by aaronbeall** [comment]
Thanks. Still, why would it be desirable to remove fills? And why by default when it's likely to alter the appearance of an svg?On Oct 14, 2017 2:46 PM, Maxime Thirouin <notifications@github.com> wrote:See https://github.com/MoOx/react-svg-inline#cleanup.
It's a default behavior that you can adjust.

**Comment by MoOx** [comment]
A common use case I had back in time was to use icons for various site. Some contains hardcoded fill to black or other colors. A common usage for me was to use this icon with a single color, so when I coded this package I made a cleanup of icons + send a color via the "fill" props.
This make icons easily adjustable without having to edit the files.

**Comment by aaronbeall** [comment]
Yeah, makes sense and that's a common use case for me, only I guess I'm used to cleaning icon SVGs ahead of time... would it be possible to only strip fills if  a `color` prop is set?

**Comment by MoOx** [comment]
Not possible with current code, you may need to tweak things a bit more :)
