### ISSUE TITLE
I'm using webpack and I'm getting a <span> as output

### ISSUE THREAD

**Issue by holgersindbaek** [MoOx/react-svg-inline#20]
I'm trying to inline my SVG's using this library, but I'm not getting any SVG's. Only span's with the svg path in them.

This is my code:

    import SVGInline from 'react-svg-inline'
    import starPath from './assets/star.svg'

    <SVGInline svg={starPath} />

And this is how my environment.js looks (I'm using Rails 5.1 with webpacker):

    const { environment } = require('@rails/webpacker')

    environment.loaders.set('json', {
      test: /\.svg$/,
      use: 'raw-loader'
    })

    module.exports = environment

And this is my output:

    <span class="SVGInline">/packs/components/Header/assets/star-9e223cf57b348993582090a549f0fc40.svg</span>

Any suggestions as to what I might be doing wrong?

**Comment by MoOx** [comment]
Looks like you also got file loader that catch your svg first. Try adjusting your configuration to not have any loader except this one for svg.
