### ISSUE TITLE
Any suggestions for dealing with conflicting SVG IDs?

### ISSUE THREAD

**Issue by shepmaster** [MoOx/react-svg-inline#29]
I just spent a few days hunting down the fact that I had an existing SVG with:

```svg
<defs>
  <ellipse id="a" cx="6" cy="6" rx="6" ry="6"></ellipse>
</defs>
```

And then I added a new SVG with:

```svg
<defs>
  <ellipse id="a" cx="16" cy="16" rx="16" ry="16"></ellipse>
</defs>
```

The usages of `#a` in the second SVG were all using the definition from the first SVG, causing much confusion.

The current workaround is to ensure that all of our source files have unique ids, but is there
something more automatic that we could do here? 

It appears that tools like [SVGInjector](https://github.com/iconic/SVGInjector) or [SVGInject](https://github.com/iconfu/svg-inject) add unique prefixes to the IDs and their usages (see also [conflicting ids in two different SVG files included in the same HTML document](https://stackoverflow.com/q/14773940/155423)).

**Comment by MoOx** [comment]
I have not idea & don't think this lib should help with that. Sorry.
