### ISSUE TITLE
UMD Build?

### ISSUE THREAD

**Issue by VinSpee** [MoOx/react-svg-inline#8]
Hi!

Would you consider publishing a UMD build? I'm using an old build system that uses `require.js`, and I can not get this package to work, even if I try to build it as a UMD module with browserify (has an issue finding `classnames`).

**Comment by MoOx** [comment]
Try using webpack. I don't plan to publish an UMD build, sorry.

**Comment by VinSpee** [comment]
ok, thanks anyway!
